version: 2.1

executors:
  unit-tests-executor:
    docker:
      - image: ress059/cclasses:latest

jobs:
  build-and-run-unit-tests:
    executor: unit-tests-executor
    steps:
      - checkout
      - run:
          name: Build Tests
          command: cd ./tests && make all

      - run:
          name: Run Ring Buffer Static Unit Tests
          command: ./tests/builds/test_ring_buffer_static.out

workflows:
  build-and-run-unit-tests:
    jobs:
      - build-and-run-unit-tests
      # - run-tests:
      #     requires:
      #       - build-tests