version: 2.1

executors:
  docker-executor:
    docker:
      - image: ress059/cclasses:latest

jobs:
  build-tests:
    # Use Docker Image for this Build Job. Go to Home Ubuntu directory once Image is opened. 
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Go into 'tests' Folder
          command: cd ./tests
      - run:
          name: Debugging. List all files in 'tests' Folder
          command: ls -l
      - run:
          name: Build Tests
          command: make all

  run-tests:
    executor: docker-executor
    steps:
      - run:
          name: Run Ring Buffer Static Unit Tests
          command: ./builds/test_ring_buffer_static.out

workflows:
  build-and-run-tests:
    jobs:
      - build-tests
      - run-tests:
          requires:
            - build-tests