version: 2.1

executors:
  unit-tests-executor:
    docker:
      - image: ress059/cclasses:latest
    working_directory: ~/project

jobs:
  build-tests:
    executor: unit-tests-executor
    steps:
      - checkout
      - run:
          name: List all folders in ~/project for debugging.......
          command: ls -l
      - run:
          name: Go into 'tests' Directory
          command: cd ./tests
      - run:
          name: Debugging. List all files in 'tests' Folder......
          command: ls -l
      - run:
          name: Build Tests
          command: make all

  run-tests:
    executor: unit-tests-executor
    steps:
      - run:
          name: Go into tests/builds/ Directory
          command: cd ./tests/builds
      - run:
          name: Run Ring Buffer Static Unit Tests
          command: ./test_ring_buffer_static.out

workflows:
  build-and-run-tests:
    jobs:
      - build-tests
      - run-tests:
          requires:
            - build-tests