version: 2.1

executors:
  unit-tests-executor:
    docker:
      - image: ress059/cclasses:latest

jobs:
  build-tests:
    executor: unit-tests-executor
    steps:
      - checkout
      - run:
          name: Go into 'tests' Directory and list all files in 'test' folder......
          command: cd ./tests && ls -l
      - run:
          name: Build Tests
          command: cd ./tests && make all

  run-tests:
    executor: unit-tests-executor
    steps:
      - run:
          name: Run Ring Buffer Static Unit Tests
          command: ./tests/builds/test_ring_buffer_static.out

workflows:
  build-and-run-tests:
    jobs:
      - build-tests
      - run-tests:
          requires:
            - build-tests